In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

5.1.
Вычислите, по возможности не используя программирование:
(5Е)–1, где Е – единичная матрица размера 5х5.

1)  E=[[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]]
       
2)При умножении матрицы на скаляр умножается каждый элемент. Е*5 - будет матрица той же формы,
единицы заменятся на 5.

3) Минус 1 =>  каждый элемент - 1:
      [[ 4, -1, -1, -1, -1],
       [-1,  4, -1, -1, -1],
       [-1, -1,  4, -1, -1],
       [-1, -1, -1,  4, -1],
       [-1, -1, -1, -1,  4]]

5.2.
Вычислите определитель: [[1, 2, 3], [4, 0, 6], [7, 8, 9]]

In [2]:
Ar1 = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
det1 = np.linalg.det(Ar1)
print(det1)

59.999999999999986


5.3.
1. Вычислите матрицу, обратную данной: [[1, 2, 3], [4, 0, 6], [7, 8, 9]]

In [3]:
I1 = np.linalg.inv(Ar1)
print(I1)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


2. Приведите пример матрицы 4х4, ранг которой равен 1.

In [4]:
R1 = np.array([[2, 5, 3, 8],
               [-4, -10, -6, -16],
               [1, 2.5, 1.5, 4],
               [-1, -2.5, -1.5, -4]])
np.linalg.matrix_rank(R1)

1

5.4.
Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)

In [5]:
#(1, 5)*(2, 8) = 1*2 + 5*8 = 42

5.5
Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 


In [6]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])
M = np.vstack((a,b,c))
M

array([[1. , 5. , 0. ],
       [2. , 8. , 7. ],
       [7. , 1.5, 3. ]])

In [7]:
np.linalg.det(M)

228.50000000000009

In [8]:
# Cмешанное произведение трех векторов: (1, 5, 0), (2, 8, 7) и (7, 1.5, 3) = 228.5

6.1. Решите линейную систему: [[1, 2, 3], [4, 0, 6], [7, 8, 9]] * X = [12,2,1]

In [9]:
#Решение методом подстановки:

#    x1 + 2*x2 + 3*x3 = 12
#    4*x1 + 6*x3 = 2
#    7*x1 + 8*x2 + 9*x3 = 1
    
#x1 = -46/5 = -9.2
#x2 = 9/10 = 0.9
#x3 = 97/15 = 6.4666666667

In [10]:
# решение средствами python
B = np.array([12,2,1])
np.linalg.solve(Ar1, B)

array([-9.2       ,  0.9       ,  6.46666667])

6.2. Найдите псевдорешение:

x + 2y – z = 1

3x – 4y = 7

8x – 5y + 2z = 12

2x – 5z = 7

11x +4y – 7z = 15

In [11]:
Ar2 = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B2 = np.array([1, 7, 12, 7, 15])

In [12]:
np.linalg.lstsq(Ar2, B2)

C:\Users\Армик\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [13]:
check = np.dot(Ar2, [ 1.13919353, -0.90498444, -0.9009803 ])

In [14]:
check - B2

array([-0.76979505,  0.03751835, -0.16349016, -0.21671144,  0.21805317])

6.3. Сколько решений имеет линейная система:
    [[1, 2, 3],
     [4, 5, 6], 
     [7, 8, 9]]
     * X =
     [12, 2, 1]

In [15]:
Ar3 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
B3 = np.array([[12, 2, 1]])
C3 = np.concatenate((Ar3, B3.T), axis=1)
print(np.linalg.matrix_rank(Ar3), np.linalg.matrix_rank(C3))

2 3


Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 

In [16]:
Ar3 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
B3_1 = np.array([4, 7, 10])

In [17]:
np.linalg.solve(Ar3, B3_1)

array([-2.,  3.,  0.])

In [18]:
import scipy
import scipy.linalg

6.4. Вычислите LU-разложение матрицы:
               [[1, 2, 3],
                [2, 16, 21],
                [4, 28, 73]]

In [19]:
Ar4 = np.array([[1, 2, 3],
                [2, 16, 21],
                [4, 28, 73]])
P, L, U = scipy.linalg.lu(Ar4)
print('Matrix L = ', L)
print('Matrix U = ', U)

Matrix L =  [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
Matrix U =  [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [20]:
B4 = np.array([3, 6, 12])
np.linalg.solve(Ar4, B4)

array([ 3., -0., -0.])

6.5. Найдите нормальное псевдорешение недоопределенной системы:

x + 2y – z = 1

8x – 5y + 2z = 12