In [1]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.array([i for i in range(12,24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a1 = a.reshape(2, 6)
a2 = a.reshape(4, 3)
a3 = a.reshape(3, 4)
a4 = a.reshape(12, 1)
a5 = a.reshape(6, 2)

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
a1 = a.reshape(2, -1)
a2 = a.reshape(4, -1)
a3 = a.reshape(-1, 4)
a4 = a.reshape(-1, 1)
a5 = a.reshape(6, -1)

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? Нет. a4.ndim даст размерность 2. Поведение также будет разное. Например при сложении одномерного массива и вектор-столбца результатом будет матрица 12 на 12. При сложении двух двумерных массивов с 12 столбцами и 1 строкой (двух вектор-столбцов) = сложение матриц; результат - матрица той же размерности, что исходные.

In [5]:
a4

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [6]:
a + a4

array([[24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37],
       [27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
       [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46]])

In [7]:
b = a.reshape(-1, 1)

In [8]:
b + a4

array([[24],
       [26],
       [28],
       [30],
       [32],
       [34],
       [36],
       [38],
       [40],
       [42],
       [44],
       [46]])

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения 
со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [9]:
a_5 = np.random.randn(3, 4)
a_5


array([[-0.77138498, -0.05893968, -0.40316224,  0.70410462],
       [ 0.33051281,  0.46258135,  0.87629636,  0.90699221],
       [ 0.32565121,  2.03830831, -1.20718083, -0.20125794]])

In [10]:
a_flat = a_5.flatten()
a_flat

array([-0.77138498, -0.05893968, -0.40316224,  0.70410462,  0.33051281,
        0.46258135,  0.87629636,  0.90699221,  0.32565121,  2.03830831,
       -1.20718083, -0.20125794])

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
В чем разница между массивами a и b? Думаю,что только формально. Мне кажется, что вести себя будут одинаково. Похоже, что а - вектор -  частный случай матрицы (одна ее строка).

In [11]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [12]:
b = np.resize((np.arange(20, 0, -2)),(1, 10))
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

7. Вертикально соединить массивы a и b. a - двумерный массив из нулей, 
число строк которого больше 1 и на 1 меньше, чем число строк двумерного 
массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.

In [13]:
a = np.zeros((2,3))
b = np.ones((3,3))

In [14]:
a_b_ver = np.vstack((a,b))
a_b_ver

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

8. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 
4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B?
Получится ли вычислить обратную матрицу для матрицы B и почему?

In [15]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
A = a.reshape(4, 3)

In [17]:
At = A.transpose()

In [18]:
B = np.dot(A, At)

Изначально линейная зависимость строк. В - квадратная матрица, сохранившая зависимость - вырожденная матрица

In [19]:
B.shape

(4, 4)

In [20]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

9. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. 
Создайте одномерный массив c, составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C.
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [21]:
np.random.seed(42)

In [22]:
c = np.random.randint(0, 16, 16)
C = c.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [23]:
D = B + C*10

In [24]:
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [25]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [26]:
np.linalg.det(D)

-28511999.999999944

In [27]:
np.linalg.matrix_rank(D)

4

10. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
Убедитесь, что в матрице D_inv остались только нули и единицы.
С помощью функции numpy.where, используя матрицу D_inv в качестве маски,
а матрицы B и C - в качестве источников данных,
получите матрицу E размером 4x4. 
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1,
должны быть равны соответствующему элементу матрицы B,
а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0,
должны быть равны соответствующему элементу матрицы C.

In [28]:
D_inv[D_inv<0] = 0
D_inv[D_inv>0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [29]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])